name: personal_website
services:
  frontend:
    container_name: frontend_personal
    image: frontend
    restart: always
    environment: 
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
    ports:
      - "80:80"
    volumes:
      - ./personal/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./personal/nginx:/usr/share/nginx/html/nginx
    networks:
      - personal_network
  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=${SQL_DB}
      - MYSQL_USER=${SQL_USR}
      - MYSQL_PASSWORD=${SQL_PASS}
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASS}  
    ports:
      - "3306:3306"
    volumes:
      - dbs:/var/lib/mysql
    networks:
      - personal_network
  backend:
    container_name: backend_personal
    image: backend
    restart: always
    environment:
      SQL_HOST: ${SQL_HOST}
      SQL_PORT: ${SQL_PORT}
      SQL_DB: ${SQL_DB}
      SQL_USR: ${SQL_USR}
      SQL_PASS: ${SQL_PASS}
    ports:
      - "3000:3000"
    networks:
      - personal_network
    depends_on:
      - db
networks:
  personal_network:
volumes:
  dbs:

